config/routes.rb
Rails.application.routes.draw do

root 'members#index'
resources :members do
  resources :comments
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :members
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :comments, dependent: :destroy

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @member = Member.find(params[:member_id])
    @comment = @member.comments.create(comment_params)
    redirect_to member_path(@member)
  end

  def destroy
    @member = Member.find(params[:member_id])
    @comment = @member.comments.find(params[:id])
    @comment.destroy
    redirect_to member_path(@member)
  end


  private

  def comment_params
    params.require(:comment).permit(:title,:message)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_action :find_member, only: [:edit,:show,:update,:destroy]
  def index
    @members = Member.all
    @categories = Category.all.map {|c| [c.name, c.id]}
  end

  def new
    @member = Member.new
    @categories = Category.all.map {|c| [c.name, c.id]}
  end

  def create
    @member = Member.new(member_params)
    @member.save
    flash[:notice] = "Created Article"
    redirect_to members_path
  end

  def edit
    @categories = Category.all.map {|c| [c.name, c.id]}
  end

  def update
    if @member.update(member_params)
      flash[:notice] = "Updated Article"
      redirect_to members_path
    else
      render 'edit'
    end

  end

  def destroy
    @member.destroy
    redirect_to members_path
  end

  def show
  end

private

def member_params
  params.require(:member).permit(:firstname,:lastname,:number,:image,:category_id)
end

def find_member
  @member = Member.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yd90</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>


        <div class="flash animated slideInLeft">
          <% flash.each do |name,msg| %>
            <%= msg %>
          <% end %>
        </div>


      <%= link_to 'home', members_path %>
    <%= yield %>




      <script type="text/javascript">
    $(document).ready(function(){
      setTimeout(function(){
      $('.flash').fadeOut();
    }, 4200);
    })




    </script>

  </body>
</html>

app/views/members/edit.html.erb
<%= form_for @member do |m| %>

  <%= m.file_field :image %>

  <%= m.label :firstname %>
  <%= m.text_field :firstname %>

  <%= m.label :lastname %>
  <%= m.text_field :lastname %>

  <%= m.label :number %>
  <%= m.text_field :number %>

  <%= m.select :category_id, @categories %>

  <%= m.submit class: "submitter"%>

<% end %>

app/views/members/index.html.erb
<ul>
  <li>Rider</li>
  <li>Class</li>
  <li>Standing</li>
</ul>

<span>Comments: </span><span class="commentsNumber"><%= Comment.all.count %></span>

<table>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
  <tbody>
<% @members.each do |m| %>
<tr>
  <td><%= link_to m.firstname, member_path(m) %></td>
  <td><%= m.lastname %></td>
  <td><%= m.number %></td>
  <td><%= m.comments.count %></td>
    <td>
      <% m.comments.each do |mc| %>
      <span id="linkers"><%= mc.title %></span>
      <% end %>

    </td>

  <td><%= m.category.name %></td>

  <td><%= link_to 'edit', edit_member_path(m) %></td>
  <td><%= link_to 'delete', member_path(m), method: :delete, data: {confirm: "Are you sure?"} %></td>
</tr>


<% end %>
</tbody>
</table>
<br>
<%= link_to 'new', new_member_path %>

app/views/members/new.html.erb
<%= form_for @member, url: members_path, html: { multipart: true } do |m| %>

<p></p>
<h1>
  <%= m.file_field :image, class: "imageUploaderText"%></h1>

  <%= m.label :firstname %>
  <span class="inputBg"> <%= m.text_field :firstname%></span><br>

  <%= m.label :lastname %>
  <%= m.text_field :lastname %><br>

  <%= m.label :number %>
  <%= m.text_field :number %><br><br>

  <%= m.select :category_id, options_for_select(@categories) %>

  <%= m.submit class: "submitter"%>

<% end %>

app/views/members/show.html.erb
<%= @member.firstname %>
<%= @member.lastname %>
<%= @member.number %>

<%= image_tag @member.image.url(:medium), class:"profileImage" %>


<%= form_for ([@member, @member.comments.build]) do |c| %>

  <%= c.label :title %>
  <%= c.text_field :title %>

  <%= c.label :message %>
  <%= c.text_field :message %>

  <%= c.submit class: "submitter" %>

<% end %>

<% @member.comments.each do |cc| %>
  <% next unless cc.persisted? %>
  <%= cc.title %>
  <%= cc.message %>
  <%= link_to 'delete', [cc.member, cc], method: :delete, data:{confirm:"Are you sure?"} %>
  <%= "#{time_ago_in_words(cc.created_at)} ago"%>
  <br>

<% end %>